# Generated by Django 3.0.2 on 2020-03-23 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='recorddetail',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='交易记录', to='trade.Record'),
        ),
        migrations.AddField(
            model_name='record',
            name='owner',
            field=models.ForeignKey(help_text='出售者', on_delete=django.db.models.deletion.CASCADE, related_name='提交者', to=settings.AUTH_USER_MODEL, verbose_name='提交者'),
        ),
        migrations.AddField(
            model_name='record',
            name='trade',
            field=models.ForeignKey(help_text='交易信息', on_delete=django.db.models.deletion.CASCADE, related_name='交易信息', to='trade.Trade', verbose_name='交易信息'),
        ),
    ]
