# Generated by Django 3.0.2 on 2020-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_buy_buyrecord_sell_sellrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'ordering': ['-date'], 'verbose_name': '交易表', 'verbose_name_plural': '交易表'},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['-date'], 'verbose_name': '交易表', 'verbose_name_plural': '交易表'},
        ),
        migrations.AddField(
            model_name='buy',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='serial_no',
            field=models.CharField(default='20200326151706-2-1585207026', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell',
            name='serial_no',
            field=models.CharField(default='20200326151706-1-1585207026', max_length=50),
        ),
    ]
