# Generated by Django 3.0.2 on 2020-03-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20200326_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time'),
        ),
        migrations.AddField(
            model_name='buyrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time'),
        ),
        migrations.AddField(
            model_name='sell',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time'),
        ),
        migrations.AddField(
            model_name='sellrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='serial_no',
            field=models.CharField(default='20200326162106-2-1585210866', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell',
            name='serial_no',
            field=models.CharField(default='20200326162106-1-1585210866', max_length=50),
        ),
    ]
