# Generated by Django 3.0.2 on 2020-03-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20200326_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrecord',
            name='serial_no',
            field=models.CharField(default='20200326172609-4-1585214769', max_length=50),
        ),
        migrations.AddField(
            model_name='sellrecord',
            name='serial_no',
            field=models.CharField(default='20200326172609-3-1585214769', max_length=50),
        ),
        migrations.AlterField(
            model_name='buy',
            name='serial_no',
            field=models.CharField(default='20200326172609-2-1585214769', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell',
            name='serial_no',
            field=models.CharField(default='20200326172609-1-1585214769', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待付款'), (1, '已付款'), (2, '取消'), (3, '已完成')], default=0, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='SellDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('order', models.CharField(max_length=50)),
                ('record', models.OneToOneField(help_text='出售记录', on_delete=django.db.models.deletion.CASCADE, to='trade.SellRecord', verbose_name='record_id')),
            ],
            options={
                'verbose_name': '出售完善的信息',
                'verbose_name_plural': '出售完善的信息',
            },
        ),
        migrations.CreateModel(
            name='BuyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time')),
                ('order', models.CharField(max_length=50)),
                ('record', models.OneToOneField(help_text='出售记录', on_delete=django.db.models.deletion.CASCADE, to='trade.SellRecord', verbose_name='record_id')),
            ],
            options={
                'verbose_name': '收购完善的信息',
                'verbose_name_plural': '收购完善的信息',
            },
        ),
    ]
