# Generated by Django 3.0.2 on 2020-03-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20200326_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='serial_no',
            field=models.CharField(default='20200326185708-2-1585220228', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyrecord',
            name='serial_no',
            field=models.CharField(default='20200326185708-4-1585220228', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell',
            name='serial_no',
            field=models.CharField(default='20200326185708-1-1585220228', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellrecord',
            name='serial_no',
            field=models.CharField(default='20200326185708-3-1585220228', max_length=50),
        ),
    ]
