# Generated by Django 3.0.2 on 2020-03-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20200326_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.FloatField(default=0, help_text='收购单价', verbose_name='buy_price'),
        ),
        migrations.AddField(
            model_name='sell',
            name='price',
            field=models.FloatField(default=0, help_text='出售单价', verbose_name='sell_price'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='serial_no',
            field=models.CharField(default='20200326203236-2-1585225956', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyrecord',
            name='serial_no',
            field=models.CharField(default='20200326203236-4-1585225956', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell',
            name='serial_no',
            field=models.CharField(default='20200326203236-1-1585225956', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellrecord',
            name='serial_no',
            field=models.CharField(default='20200326203236-3-1585225956', max_length=50),
        ),
    ]
