# Generated by Django 3.0.2 on 2020-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_auto_20200328_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='serial_no',
            field=models.CharField(default='20200329093529-2-1585445729', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyrecord',
            name='serial_no',
            field=models.CharField(default='20200329093529-4-1585445729', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell',
            name='serial_no',
            field=models.CharField(default='20200329093529-1-1585445729', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellrecord',
            name='serial_no',
            field=models.CharField(default='20200329093529-3-1585445729', max_length=50),
        ),
    ]
