# Generated by Django 3.0.2 on 2020-01-13 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('model_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一的id', primary_key=True, serialize=False, verbose_name='model id')),
                ('name', models.CharField(help_text='名称信息', max_length=50, verbose_name='名称')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '类别1',
                'verbose_name_plural': '类别1',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '测试',
                'verbose_name_plural': '测试',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('model_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一的id', primary_key=True, serialize=False, verbose_name='model id')),
                ('name', models.CharField(help_text='名称信息', max_length=50, verbose_name='名称')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('code', models.CharField(blank=True, default='', help_text='类别code', max_length=30, verbose_name='类别代码')),
                ('desc', models.CharField(blank=True, default='', help_text='类别描述', max_length=30, verbose_name='类别描述')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '类别1'), (2, '类别2'), (3, '类别3'), (4, '类别4')], verbose_name='类型')),
                ('is_tab', models.BooleanField(default=False, help_text='是否是导航', verbose_name='是否是导航')),
                ('parent', models.ForeignKey(blank=True, default='', help_text='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Category', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '类别表',
                'verbose_name_plural': '类别表',
            },
        ),
    ]
