# Generated by Django 3.0.1 on 2020-01-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='discount',
            field=models.PositiveSmallIntegerField(default=100, help_text='折扣', verbose_name='折扣'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='标价', max_digits=8, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='num',
            field=models.CharField(default='2020-01-03 13:26:12', help_text='订单号，如果没有订单号的时候会默认设置成日期', max_length=100, verbose_name='订单号'),
        ),
    ]
