# Generated by Django 3.0.1 on 2020-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato_admin', '0002_auto_20200103_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='desc',
            field=models.CharField(blank=True, help_text='商品的介绍信息', max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='num',
            field=models.CharField(default='2020-01-03 18:03:06', help_text='订单号，如果没有订单号的时候会默认设置成日期', max_length=100, verbose_name='订单号'),
        ),
    ]
