# Generated by Django 3.0.1 on 2020-01-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato_admin', '0005_auto_20200104_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='num',
            field=models.CharField(default='2020-01-04 18:24:39', help_text='订单号，如果没有订单号的时候会默认设置成日期', max_length=100, verbose_name='订单号'),
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('name', 'title')},
        ),
    ]
