# Generated by Django 3.0.1 on 2020-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato_admin', '0006_auto_20200104_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='num',
            field=models.CharField(default='2020-01-04 18:31:11', help_text='订单号，如果没有订单号的时候会默认设置成日期', max_length=100, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='purchaseorderprice',
            name='num',
            field=models.PositiveSmallIntegerField(help_text='货物的数量', verbose_name='数量 个/套'),
        ),
    ]
