# Generated by Django 3.0.2 on 2020-03-28 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200328_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinuserinfo',
            name='address',
            field=models.CharField(default=uuid.UUID('6c104f09-c56f-5eb7-998b-d23b014d1369'), help_text='地址', max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='coinuserinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='created_time'),
        ),
    ]
