# Generated by Django 3.0.2 on 2020-03-28 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200328_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinuserinfo',
            name='address',
            field=models.CharField(default=uuid.UUID('978ceebc-0521-5de0-9e31-1ef33546bc29'), help_text='地址', max_length=100, verbose_name='地址'),
        ),
    ]
