# Generated by Django 3.0.2 on 2020-03-28 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200328_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinuser',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='coinuserinfo',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.AlterField(
            model_name='coinuserinfo',
            name='address',
            field=models.CharField(default=uuid.UUID('15cdbdd3-4f18-5049-9b8e-601a9996eaa7'), help_text='地址', max_length=100, verbose_name='地址'),
        ),
    ]
