# Generated by Django 3.0.2 on 2020-03-28 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200328_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinuserinfo',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='coinuserinfo',
            name='frozen',
        ),
        migrations.AlterField(
            model_name='coinuserinfo',
            name='address',
            field=models.CharField(default=uuid.UUID('22a8785d-ab7d-5365-ba3f-6ca4b26469b9'), help_text='地址', max_length=100, verbose_name='地址'),
        ),
    ]
