# Generated by Django 3.0.2 on 2020-03-29 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200328_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinuserinfo',
            name='address',
            field=models.CharField(default=uuid.UUID('87e25954-8896-57ba-b32e-61929c7b4734'), help_text='地址', max_length=100, verbose_name='地址'),
        ),
    ]
