# Generated by Django 3.0.2 on 2020-03-29 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200329_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinuserinfo',
            name='address',
            field=models.CharField(default=uuid.UUID('27bbfa23-2d02-5286-830e-11a6eda6740b'), help_text='地址', max_length=100, verbose_name='地址'),
        ),
    ]
