# Generated by Django 3.0.2 on 2020-03-29 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200329_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinuserinfo',
            name='address',
            field=models.CharField(default=uuid.UUID('d4f70473-4ee6-53ad-9c88-e834c5c03121'), help_text='地址', max_length=100, verbose_name='地址'),
        ),
    ]
