# Generated by Django 3.0.2 on 2020-03-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=20, unique=True, verbose_name='标题')),
                ('count', models.PositiveIntegerField(help_text='数量', verbose_name='数量')),
            ],
            options={
                'verbose_name': '矿机表',
                'verbose_name_plural': '矿机表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='machine.Machine')),
            ],
            options={
                'verbose_name': '矿机租赁列表',
                'verbose_name_plural': '矿机租赁列表',
            },
        ),
    ]
