# Generated by Django 3.0.2 on 2020-03-13 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='users',
            field=models.ManyToManyField(through='machine.Record', to=settings.AUTH_USER_MODEL),
        ),
    ]
