# Generated by Django 3.0.2 on 2020-03-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=60, verbose_name='标题')),
                ('img', models.CharField(blank=True, default='', help_text='图片', max_length=256, verbose_name='图片')),
                ('url', models.CharField(blank=True, default='', help_text='文章链接', max_length=256, verbose_name='文章链接')),
                ('datetime', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻表',
                'verbose_name_plural': '新闻表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, help_text='记录的时间', verbose_name='时间')),
                ('news', models.ForeignKey(help_text='新闻id', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.Content', verbose_name='新闻')),
            ],
            options={
                'verbose_name': '新闻观看记录',
                'verbose_name_plural': '新闻观看记录',
            },
        ),
    ]
