# Generated by Django 3.0.2 on 2020-03-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ALI', '支付宝'), ('BANK', '银行卡')], max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '支付信息',
                'verbose_name_plural': '支付信息',
            },
        ),
    ]
