# Generated by Django 3.0.2 on 2020-03-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_pay_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='use',
            field=models.BooleanField(default=True, help_text='是否在使用', verbose_name='use_state'),
        ),
    ]
