# Generated by Django 3.0.2 on 2020-01-26 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('title', models.CharField(help_text='标题', max_length=30, unique=True, verbose_name='标题')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('title', models.CharField(default='', help_text='标题', max_length=30, verbose_name='标题')),
                ('sub_title', models.CharField(blank=True, default='', help_text='子标题', max_length=50, verbose_name='子标题')),
                ('price', models.FloatField(default=0.0, help_text='价格', verbose_name='价格')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '售空'), (1, '出售中'), (2, '补货中')], default=1)),
                ('qr_code', models.CharField(blank=True, default='', help_text='二维码标签上的信息如果有的话', max_length=20, verbose_name='二维码')),
                ('desc', models.CharField(blank=True, default='', help_text='描述信息', max_length=100, verbose_name='描述')),
                ('category', models.ForeignKey(blank=True, help_text='分类信息', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('url', models.ImageField(blank=True, default='', help_text='展示的图片', upload_to='img', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图像',
                'verbose_name_plural': '图像',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('u_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一的id', primary_key=True, serialize=False, verbose_name='model id')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('title', models.CharField(max_length=50)),
                ('total', models.FloatField(help_text='订单需要的价格', verbose_name='总价')),
                ('order_num', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('title', models.CharField(help_text='标题', max_length=30, unique=True, verbose_name='标题')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('u_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一的id', primary_key=True, serialize=False, verbose_name='model id')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('total', models.FloatField(help_text='订单需要的价格', verbose_name='总价')),
                ('order_num', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': '用户订单',
                'verbose_name_plural': '用户订单',
            },
        ),
        migrations.CreateModel(
            name='UserOrderInfo',
            fields=[
                ('u_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一的id', primary_key=True, serialize=False, verbose_name='model id')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='商品价格', max_digits=8, verbose_name='价格')),
                ('num', models.PositiveSmallIntegerField(blank=True, default=1, help_text='商品的数量', verbose_name='商品数量')),
                ('commodity', models.ForeignKey(help_text='商品的ID', on_delete=django.db.models.deletion.CASCADE, to='myapi.Commodity', verbose_name='商品ID')),
                ('order', models.ForeignKey(help_text='订单的ID', on_delete=django.db.models.deletion.CASCADE, to='myapi.UserOrder', verbose_name='订单ID')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.AddField(
            model_name='userorder',
            name='commodity_list',
            field=models.ManyToManyField(help_text='订单内所有的商品的信息', through='myapi.UserOrderInfo', to='myapi.Commodity', verbose_name='订单的商品信息'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(help_text='订单信息用户名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='订单用户名'),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('u_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一的id', primary_key=True, serialize=False, verbose_name='model id')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('name', models.CharField(help_text='商家名称', max_length=50, verbose_name='商家名')),
                ('nick_name', models.CharField(blank=True, default='', help_text='商家名称', max_length=50, verbose_name='商家名称')),
            ],
            options={
                'verbose_name': '商家信息',
                'verbose_name_plural': '商家信息',
                'unique_together': {('name', 'nick_name')},
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('u_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一的id', primary_key=True, serialize=False, verbose_name='model id')),
                ('updated', models.DateTimeField(auto_now=True, help_text='最新的更新日期', verbose_name='最新更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='商品价格', max_digits=8, verbose_name='价格')),
                ('num', models.PositiveSmallIntegerField(blank=True, default=1, help_text='商品的数量', verbose_name='商品数量')),
                ('commodity', models.ForeignKey(help_text='商品的ID', on_delete=django.db.models.deletion.CASCADE, to='myapi.Commodity', verbose_name='商品ID')),
                ('order', models.ForeignKey(help_text='订单的ID', on_delete=django.db.models.deletion.CASCADE, to='myapi.Order', verbose_name='订单ID')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='commodity_list',
            field=models.ManyToManyField(help_text='订单内所有的商品的信息', through='myapi.OrderInfo', to='myapi.Commodity', verbose_name='订单的商品信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, default='', help_text='卖家的订单', on_delete=django.db.models.deletion.CASCADE, to='myapi.Seller', verbose_name='卖家'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='图片信息', to='myapi.Image', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='标签', to='myapi.Tag', verbose_name='标签'),
        ),
    ]
