# Generated by Django 3.0.2 on 2020-03-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=60, verbose_name='标题')),
                ('img', models.CharField(blank=True, default='', help_text='图片', max_length=256, verbose_name='图片')),
                ('url', models.CharField(blank=True, default='', help_text='文章链接', max_length=256, verbose_name='文章链接')),
                ('content', models.CharField(blank=True, default='', help_text='广告内容', max_length=120, verbose_name='广告内容')),
                ('datetime', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '新闻表',
                'verbose_name_plural': '新闻表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='新闻', to='advert.Content')),
            ],
            options={
                'verbose_name': '新闻表',
                'verbose_name_plural': '新闻表',
                'ordering': ['id'],
            },
        ),
    ]
