# Generated by Django 3.0.2 on 2020-03-14 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=60, verbose_name='标题')),
                ('img', models.CharField(blank=True, default='', help_text='图片', max_length=256, verbose_name='图片')),
                ('url', models.CharField(blank=True, default='', help_text='文章链接', max_length=256, verbose_name='文章链接')),
                ('content', models.CharField(blank=True, default='', help_text='广告内容', max_length=120, verbose_name='广告内容')),
            ],
            options={
                'verbose_name': '新闻表',
                'verbose_name_plural': '新闻表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='新闻', to='advert.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='读者', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '新闻表',
                'verbose_name_plural': '新闻表',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='readers',
            field=models.ManyToManyField(related_name='阅读者', through='advert.Record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发布者', to=settings.AUTH_USER_MODEL, verbose_name='用户信息'),
        ),
    ]
