# Generated by Django 3.0.2 on 2020-03-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='奖励的key 根据key进行搜索是否有存在', max_length=50, unique=True, verbose_name='奖励的key')),
                ('coin', models.FloatField(help_text='奖励或者需要扣除', verbose_name='奖励的分数')),
                ('percent', models.FloatField(default=0.0, help_text='必须用来购物的百分比', verbose_name='必须用来购物的部分')),
                ('type', models.IntegerField(help_text='奖励的类型', verbose_name='奖励的类型')),
                ('freq', models.IntegerField(choices=[(0, '有限次数'), (1, '每天次数'), (2, '每月的次数'), (3, '每年的次数'), (4, '未限制次数')], default=0, help_text='频率', verbose_name='频率')),
                ('freq_num', models.IntegerField(default=1, help_text='次数', verbose_name='次数')),
                ('desc', models.CharField(help_text='奖励的描述', max_length=30, verbose_name='奖励的描述')),
            ],
            options={
                'verbose_name': '奖励类型',
                'verbose_name_plural': '奖励类型',
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin1', models.FloatField(default=0, verbose_name='币种1')),
                ('coin2', models.FloatField(default=0, verbose_name='币种2')),
            ],
            options={
                'verbose_name': '货币中心',
                'verbose_name_plural': '货币中心',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('point', models.FloatField(verbose_name='获取的数量')),
                ('shop', models.FloatField(default=0, verbose_name='必须用来购物的部分，系统获得')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('desc', models.CharField(default='', help_text='说明', max_length=120, verbose_name='说明')),
            ],
            options={
                'verbose_name': '货币获取的记录',
                'verbose_name_plural': '货币获取的记录',
            },
        ),
    ]
