# Generated by Django 3.0.2 on 2020-03-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin1', models.FloatField(default=0, verbose_name='币种1')),
                ('coin2', models.FloatField(default=0, verbose_name='币种2')),
            ],
            options={
                'verbose_name': '货币中心',
                'verbose_name_plural': '货币中心',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(verbose_name='获取的数量')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('desc', models.CharField(default='', help_text='说明', max_length=120, verbose_name='说明')),
            ],
            options={
                'verbose_name': '货币获取的记录',
                'verbose_name_plural': '货币获取的记录',
            },
        ),
    ]
