# Generated by Django 3.0.2 on 2020-03-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20200312_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='奖励的key 根据key进行搜索是否有存在', max_length=50, unique=True, verbose_name='奖励的key')),
                ('coins', models.FloatField(help_text='奖励或者需要扣除', verbose_name='奖励的分数')),
                ('type', models.IntegerField(help_text='奖励的类型', verbose_name='奖励的类型')),
                ('freq', models.IntegerField(choices=[(0, '有限次数'), (1, '每天次数'), (2, '每月的次数'), (3, '每年的次数'), (4, '未限制次数')], default=0, help_text='频率', verbose_name='频率')),
                ('freq_num', models.IntegerField(default=1, help_text='次数', verbose_name='次数')),
            ],
            options={
                'verbose_name': '奖励类型',
                'verbose_name_plural': '奖励类型',
            },
        ),
    ]
