# Generated by Django 3.0.2 on 2020-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_auto_20200325_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='规则', max_length=20, verbose_name='规则名')),
                ('tax', models.FloatField(default=0, help_text='手续费 百分比', verbose_name='出售的税')),
                ('pay', models.BooleanField(default=0, help_text='是否需要支付金额, 手动去控制', verbose_name='是否需要支付')),
                ('shop', models.FloatField(default=0, help_text='获取的币 多少需要进行购物, 最大是1最小是0', verbose_name='获取币的购物百分比')),
                ('used', models.BooleanField(default=False, verbose_name='是否已经启用')),
            ],
            options={
                'verbose_name': '规则表',
                'verbose_name_plural': '规则表',
            },
        ),
    ]
