# Generated by Django 3.0.2 on 2020-03-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_auto_20200326_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrule',
            name='min_num',
            field=models.FloatField(default=0, verbose_name='剩余的最小值'),
        ),
    ]
